
- server_ip: "localhost"
- server_port: 9092

# JOB MANAGER PARAMETERS
- job_name: "job_1"

# number of task managers to connect to
- tm_number: 2
# number of copies of the pipeline
- parallelism: 2
# kafka topics replication factor
- replication_factor: 2

# input/output topics configuration
- source_topic: "source_topic"
- sink_topic: "sink_topic"