
# Global parameters
- server_ip: "localhost"
- server_port: 9092

# 'computation' name, to distinguish different computations
- group: "group_1"

# number of copies of the pipeline
- parallelism: 1
#
- replication_factor: 1
# number of partitions in each topic
- num_topics_partitions: 1