
# Global parameters

- server_ip: "localhost"
- server_port: 9092

- group: "group_1"  # 'computation' name, to distinguish different computations

- tasks_num: 2
- parallelism: 2
- replication_factor: 2
- num_topics_partitions: 2