
# Pipeline structure and nodes description

- source_topic: "source_topic"
- sink_topic: "sink_topic"

- id: "source_id"
  type: "forward"
  from: "begin"
  to: "sink_id"

- id: "sink_id"
  type: "forward"
  from: "source_id"
  to: "end"