
# Pipeline structure and nodes description

- source_topic: "source_topic"
- sink_topic: "sink_topic"

# SOURCE NODE
- id: "source_id"
  type: "forward"
  from: "source"
  to: "sink_id"

# SINK NODE
- id: "sink_id"
  type: "forward"
  from: "source_id"
  to: "sink"